# Generated by Django 4.2.26 on 2025-11-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(max_length=1000)),
                ('duruation', models.TimeField()),
                ('video_url', models.URLField()),
                ('audio_url', models.URLField()),
                ('guest', models.IntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='podcasts', to='podcasts.category')),
            ],
        ),
    ]
