# Generated by Django 4.2.26 on 2025-11-07 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to=settings.AUTH_USER_MODEL),
        ),
    ]
