# Generated by Django 5.2.7 on 2025-11-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcust', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['-published_at']},
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='duruation',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='video_url',
        ),
        migrations.AddField(
            model_name='podcast',
            name='channel_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='podcast',
            name='like_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='podcast',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='podcast',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='', help_text='YouTube Video ID (e.g., dQw4w9WgXcQ)', max_length=20, null=True, unique=True),
        ),
    ]
