# Generated by Django 5.2.7 on 2025-11-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcust', '0002_alter_podcast_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='mux_playback_id',
            field=models.CharField(blank=True, default='', help_text='Mux Playback ID for video streaming', max_length=50, null=True),
        ),
    ]
