# Generated by Django 5.2.7 on 2025-11-07 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcust', '0003_podcast_mux_playback_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='mux_playback_id',
        ),
    ]
