# Generated by Django 5.2.7 on 2025-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcust', '0004_remove_podcast_mux_playback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
